name: remote_ui
description: Flutter widget to manage UI from a JSON definition
version: 0.0.10
homepage: https://github.com/jaumard/remote_ui/tree/master/packages/remote_ui

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_hooks: ">=0.10.0 <1.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
