name: remote_image_button
description: Image button addon for remote ui package
version: 0.1.1
homepage: https://github.com/jaumard/remote_ui/tree/master/packages/remote_color_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter_sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter_svg: ">=1.0.0 <2.0.0"
  flutter_hooks: ">=0.18.0 <1.0.0"
  remote_ui: #">=0.1.0 <1.0.0"
    #path: '../remote_ui'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
